CI starter: add dockerfile for submit to g registry by gh action
NodleCode/subquery pull request #18
Opened 2022-10-31 17:52 UTC by Douglasacost

2022-10-31 20:49 UTC, noisefloors commented on Dockerfile
> +    CMD curl -f http://subquery-node:3000/ready || exit 1
```suggestion
```

2022-10-31 20:50 UTC, noisefloors commented on Dockerfile
> +HEALTHCHECK --interval=3s --timeout=5s --retries=10 \
```suggestion
```

2022-10-31 20:51 UTC, noisefloors requested changes
You can remove the `HEALTHCHECK` statement in `Dockerfile`, but that's all. Everything else looks great.

2022-10-31 22:51 UTC, Douglasacost commented
> You can remove the `HEALTHCHECK` statement in `Dockerfile`, but that's all. Everything else looks great.
> 
> The reason we don't need that is any orchestration system (Docker Compose, Kubernetes, etc.) would probably override the healthcheck externally. I believe we'd have more occasions where the static DNS host path set in the image (`subquery-node`) wouldn't resolve, than where it worked correctly.

It's done. Also removed and "bad" relation that can become to have an blocker issue

2022-11-01 06:38 UTC, noisefloors approved these changes

2022-11-01 16:41 UTC, merged